### ISSUE TITLE
Output issues

### ISSUE THREAD

**Issue by Reddynikila** [cognitive-ninja/Mini-Voting-System#1]
please provide the output screenshots of that sourcecode

**Comment by cognitive-ninja** [comment]
[Output Screenshots.zip](https://github.com/cognitive-ninja/Mini-Voting-System/files/5072497/Output.Screenshots.zip)
@Reddynikila These are the screenshots on Dev-C++ compiler. If you are using TurboC++ Compiler, comment out clrscr() statements present in the code and you will get more descent output screen.
