### ISSUE TITLE
File not included

### ISSUE THREAD

**Issue by TechieYash** [cognitive-ninja/Mini-Voting-System#2]
No file is included for the program to read contents from. The program is getting terminated upon entering a valid PRN for student login.

**Comment by rushelmac** [comment]
For using the program for first time:
1. Open Admin panel
2. Setup new election
3. Complete all necessary steps
4. And then you will be able to vote using valid PRN (Roll No.)
[ Note: Structure of PRN is year(4 char)-degree(3 char)-branch(2 char)-serial_No(5 char)
e.g. 2018btecs00001 ]
