### ISSUE TITLE
PRN issue

### ISSUE THREAD

**Issue by Arvy-believer** [cognitive-ninja/Mini-Voting-System#3]
After Entering the PRN number the program does not responds.
![Capture1](https://user-images.githubusercontent.com/70834359/97800112-a112dd80-1c58-11eb-8282-e72346038bcd.JPG)

**Comment by cognitive-ninja** [comment]
Entered same inputs and it works well. Try to do it again.

![Screenshot (542)](https://user-images.githubusercontent.com/59176822/101259600-cc08b980-374f-11eb-9013-30ccdcfcf989.png)
