### ISSUE TITLE
about prn

### ISSUE THREAD

**Issue by nil2705** [cognitive-ninja/Mini-Voting-System#6]
who to get prn?

**Comment by cognitive-ninja** [comment]
Could you please explain your doubt a little more? 
PRN here is considered as the unique id of a voter.

**Comment by nil2705** [comment]
> Could you please explain your doubt a little more?
> PRN here is considered as the unique id of a voter.
PRN IS UNIQUE ID OF VOTER SO HOW can i get my prn?

**Comment by nil2705** [comment]
also as admin  how take others prn?

**Comment by cognitive-ninja** [comment]
> > PRN IS UNIQUE ID OF VOTER SO HOW can i get my prn?
Actually, this program was developed to take classroom election so in the classroom each student has its unique roll number it makes use of that. To understand the structure of prn more clearly, refer this: https://github.com/cognitive-ninja/Mini-Voting-System/issues/4#issuecomment-812884638.

**Comment by cognitive-ninja** [comment]
> also as admin how take others prn?

As an admin, you can set a range of valid PRN. For example, your CSE class has 80 students PRN range will be from 1 to 80.
And suppose if anyone is missing from this range. For example, let's say roll no 44 and 73 are absent during the election then these PRNs are called a blank PRN and as an admin, you can eliminate them and prevent them from voting by adding them as a blank prn.

**Comment by cognitive-ninja** [comment]
And I think your main doubt is that how each student will get identified by its unique PRN? As I mentioned earlier we made use of pre-available roll numbers in college to identify each student. But if you don't want that then you can further extend the program by creating a new register module that will take data of students and will generate PRN. And further You have to maintain a new file to store this data.
