### ISSUE TITLE
after enter prn number code isn't working? kindly check header file code. error is i can't write any command. 

### ISSUE THREAD

**Issue by nil2705** [cognitive-ninja/Mini-Voting-System#7]
after enter prn number code isn't working? kindly check header file code. error is i can't write any command.

**Comment by malivinayak** [comment]
When isSpecial is called after entering 1 digit PRN complier doesn't find blank.txt file to open in read mode so compiler get stuck at that place
To check whether file is opened successfully or not you need to add some lines of code and if not opened file successfully then return with that error 
As these code is missing system stuck there only

Provide more details about PRN as I don't get which one is valid PRN for entering the prn
Also, provide blank.txt and other file handling files

**Comment by cognitive-ninja** [comment]
WIll check and correct these erroers and also I am adding short video soon to show the demo of project which will help you to clear your doubts. Still if you get a doubt ask anytime.
